import {
  PrismaClient,
  LessonType,
  Difficulty,
  AccessTier,
  ExamType,
} from "@prisma/client";

const ARTICLE_HTML = `
## Heat Energy
- Heat is the form of energy that changes the temperature in any substance.
- Heat involves the transfer of energy from an object or an energy source to another medium or an object
- Heat is always transferred from the object at the higher temperature to the object with the lower temperature
- **Units :** 
  - erg
  - joule
  - Calorie
- **Calorimetry** is used to measure the **amount of thermal energy transferred** in a **chemical or physical process**.
- The **bomb calorimeter** is an instrument used to measure the **heat of reaction** at a fixed volume.

## Heat transfer
- Any matter which is made up of atoms and molecules has the ability to transfer heat.
- The atoms are in different types of motion at any time. The motion of molecules and atoms is responsible for heat or thermal energy and every matter has this thermal energy.
- The movement of heat across the border of the system due to a difference in temperature between the system and its surroundings is called heat **transfer**.
- Eg .,The reason for the rise of mercury is that it expands on heating, when we put the bulb of thermometer under our armpit the heat of our body is transferred to the bulb which is then transferred to mercury.

### Heat conduction
- Conduction is defined as the process in which heat flows from objects with higher temperature to objects with lower temperature.
- An area of higher kinetic energy transfers thermal energy towards the lower kinetic energy area.
- High-speed particles clash with particles moving at a slow speed, as a result, slow speed particles increase their kinetic energy.
- This is a typical form of heat transfer and takes place through physical contact.
- Conduction is also known as thermal conduction or heat conduction.
**Examples**
- Ironing of clothes is an example of conduction where the heat is conducted from the iron to the clothes.
- Heat is transferred from hands to ice cubes resulting in the melting of an ice cube when held in hands.
- Heat conduction through the sand at the beaches. This can be experienced during summers. Sand is a good conductor of heat.

### Heat convection
- Convection is defined as the movement of fluid molecules from higher temperature regions to lower temperature regions.
- As the temperature of the liquid increases, the liquid's volume also has to increase by the same factor and this effect is known as displacement.
**Examples**
- Boiling of water, that is molecules that are denser move at the bottom while the molecules which are less dense move upwards resulting in the circular motion of the molecules so that water gets heated.
- Warm water around the equator moves towards the poles while cooler water at the poles moves towards the equator.
- Blood circulation in warm-blooded animals takes place with the help of convection, thereby regulating the body temperature.

### Heat radiation
- Thermal radiation is generated by the emission of electromagnetic waves.
- These waves carry away the energy from the emitting body. Radiation takes place through a vacuum or transparent medium which can be either solid or liquid.
- Thermal radiation is the result of the random motion of molecules in the matter.
- The movement of charged electrons and protons is responsible for the emission of electromagnetic radiation
**Examples**
- Microwave radiation emitted in the oven is an example of radiation.
- UV rays coming from the sun is an example of radiation.
- The release of alpha particles during the decaying of Uranium-238 into Thorium-234 is an example of radiation.
- Heat transfer at the process of radiation is very fast compared to conduction and convection.
- At the process of radiation heat transfer takes place with equal velocity of light that means c = $3 \times 10^8 m/sec$

## Applications
- A cold steel spoon is dipped in a cup of hot milk. It transfers heat to its other end by the process of Conduction.
- Earth is heated by the sun due to solar radiation.

## Thermo flask
- Thermo flask was invented by the scientist dewar
- The function of the thermos flask is to prevent the flow of heat to and from the bottle.
- We know that heat can flow from one place to another by three processes: conduction, convection and radiation. The thermos flask prevents the flow of heat by any of these processes.

## Thermal conductors
- A **thermal conductor** is a material that allows energy in the form of heat, to be transferred within the material, without any movement of the material itself.
**Examples**
- Gold, Silver, Copper, Aluminium, Iron etc are good heat conductors,

## Thermal insulators
- A **thermal insulator** is a material that does not allows energy in the form of heat, to be transferred within the material, without any movement of the material itself.
**Examples**
- Polystyrene, foam, water, mineral wool, plastic, cotton are bad heat conductors

## Temperature
- Temperature refers to the hotness or coldness of a body
- In 16th century Galileo invented the device thermometer is an instrument that measures temperature.
- It can measure the temperature of a solid such as food, a liquid such as water, or a gas such as air.
- The four most common units of measurement for temperature are
  - **Celsius**
  - **Fahrenheit**
  - **kelvin and**
  - **rankine.**
- most probably we use celsius and farenheit only

### Relation between celsius , farenheit and kelvin
- $C/100 = (F-32)/180 = (K-273)/100$
- Let us suppose that both celsius and temperature reading should be 'x'
  - $x/100 = (x-32)/180$
  - after simplification we get $x = -40$
  - hence $C = F = -40$

### Relation between celsius and kelvin
- $C/100 = (K-273)/100$
- $C = K - 273$
- Ice temperature : Celsius : 0°C ; Kelvin : 273K
- Water vapour    : Celsius : 100°C ; Kelvin : 373K
- Temperature on moon in day time : Celsius : 100°C ; Kelvin : 373K
- Healthy human being temperature : Celsius : 37°C ; Kelvin : 310K
- Pasteurization of milk : Celsius : 67°C ; Kelvin : 340K

## Types of thermometers

**Clinical thermometer**
- Clinical thermometers are meant for clinical purposes. It is developed for measuring the human body temperature.
- It is a long narrow glass tube with a bulb containing mercury at the end.
- The normal human body temperature is 37°C; which can fluctuate between the ranges 35°C to 42°C.
- Hence, the clinical thermometers have the range 35°C to 42°C.
- The level of mercury tells our body temperature to be °C.
- Since mercury is a toxic element, thus these thermometers have been replaced by digital thermometers nowadays

**Laboratory thermometer**
- A laboratory thermometer, which is also known as the lab thermometer, is used for measuring temperatures other than the human body temperature.
- It ranges from -10°C to 110°C.
- Laboratory thermometers are designed for lab purposes such as checking boiling point, freezing point, or temperature of other substances.
- we can use a laboratory thermometer for checking the temperature of a solvent but not a clinical one.

**Digital Thermometer**
- These thermometers are used for measuring the temperature by the means of an electronic circuit.
- The information captured is sent to a microchip that processes it and gets displayed numerically on the digital screen.
- They are easy to use, inexpensive, and accurate. Digital thermometers can be considered to be advanced thermometers that are used for measuring body temperature.

**Infrared Ear Thermometer**
- Checking the body temperature using the inside of the ear is known as tympanic membrane temperature.
- This method is common when the temperature needs to be taken from the children as it is quick.
- Infrared thermometer captures the temperature in the form of infrared energy given off by the heat source.
- The normal ear temperature in adults is 37.5°C

**Six's maximum and the minimum thermometer**
- Six's maximum and the minimum thermometer is mainly used for measuring the maximum and minimum temperature of the particular day.

**Bimetallic thermometer**
- The bimetallic thermometer is used in household devices like ovens, air conditioners, and in industrial apparatus like refineries, hot wires, heater, tempering tanks etc. for measuring the temperature.

**Beckmann thermometer**
- A Beckmann thermometer is a device used to measure small differences of temperature, but not absolute temperature values.
- Today its use has largely been superseded by electronic thermometers.

**Electronic Thermometer**
- Electronic thermometers detect temperature changes using a thermo resistive device in which the electrical resistance changes in response to changes in temperature.
- This device may be a thermistor or a thermocouple and is incorporated into the tip of a probe.

**Bathy scope thermometer**
- These thermometers are used to measure the temperatures under seas and oceans.

## Specific heat
- Specific heat is used when we are referring to something particular.
- Heat capacity is the ratio of the quantity of heat required to alter the temperature by one degree Celsius.
- The heat capacity of most systems is not constant and it depends on quantities like the pressure, volume and temperature.
- **Specific heat is the quantity of heat essential to raise the temperature of one gram of any substance by 1 degree Celsius.**
- Specific Heat formula is articulated as
  - $C = \Delta Q / m \Delta T$
  - Where,
  - $\Delta Q$ is the heat gained or lost
  - $\Delta T$ is the temperature difference
  - $m$ is the mass
- The temperature difference is given by $\Delta T = (T_f - T_i)$, where the final temperature is $T_f$ and the initial temperature is $T_i$.
- Specific Heat formula is made use of to find the specific heat of any given material, its mass, heat gained or temperature difference if some of the variables are given.
- It is articulated in **Joule/Kg Kelvin (J/Kg K)**.
`;

const QUESTIONS = [
  {
    questionText:
      "If 50 grams of water at 20°C is mixed with 50 grams of water at 40°C, what is the temperature of the resulting mixture?",
    options: [
      { key: "1", text: "40°C" },
      { key: "2", text: "20°C" },
      { key: "3", text: "30°C" },
      { key: "4", text: "25°C" },
    ],
    correctOption: "3",
  },
  {
    questionText: "Formula for specific heat is",
    options: [
      { key: "1", text: "S= Q/ mΔT" },
      { key: "2", text: "S= Q/m" },
      { key: "3", text: "S= QΔT/m" },
      { key: "4", text: "S= Qm/ΔT" },
    ],
    correctOption: "1",
  },
  {
    questionText:
      "100 g. of water is at 100°C. The heat required to convert the liquid water into the gaseous state is?",
    options: [
      { key: "1", text: "5400 cal" },
      { key: "2", text: "54000 kcal" },
      { key: "3", text: "540 k cal" },
      { key: "4", text: "54000cal" },
    ],
    correctOption: "4",
  },
  {
    questionText:
      "The physical quantity that indicates the change in temperature of a substance when a given amount of heat is absorbed or released by it",
    options: [
      { key: "1", text: "Specific heat capacity" },
      { key: "2", text: "Heat capacity" },
      { key: "3", text: "Latent heat" },
      { key: "4", text: "Thermal resistance" },
    ],
    correctOption: "2",
  },
  {
    questionText:
      "A clock made of brass pendulum keeps correct time at 20°C. But at 30°C it loses 8.212 s. per day. However, the coefficient of linear expansion of brass is",
    options: [
      { key: "1", text: "6×10⁻⁶/°C" },
      { key: "2", text: "9x10⁻⁶/°C" },
      { key: "3", text: "19x10⁻⁶/°C" },
      { key: "4", text: "16×10⁻⁶/°C" },
    ],
    correctOption: "3",
  },
  {
    questionText:
      "If the temperature increases by 1°C in the Celsius scale, how many degrees does it increase in the Fahrenheit scale?",
    options: [
      { key: "1", text: "1 F" },
      { key: "2", text: "2 F" },
      { key: "3", text: "1.8 F" },
      { key: "4", text: "8.1 F" },
    ],
    correctOption: "3",
  },
  {
    questionText:
      "When a piece of ice is placed on an iron block and another on a wooden block without ice, which block melts the piece of ice faster?",
    options: [
      { key: "1", text: "The one on the iron block." },
      { key: "2", text: "On a block of wood" },
      { key: "3", text: "Neither melts" },
      { key: "4", text: "Both melt simultaneously" },
    ],
    correctOption: "1",
  },
  {
    questionText:
      "What is the reason for the coldness of nail polish when it is removed with the help of a remover?",
    options: [
      { key: "1", text: "Melting" },
      { key: "2", text: "Evaporation" },
      { key: "3", text: "Deposition" },
      { key: "4", text: "Re-freezing" },
    ],
    correctOption: "2",
  },
  {
    questionText:
      "To mark 0°C on a mercury thermometer, what is the mercury bulb placed in contact with?",
    options: [
      { key: "1", text: "In boiling water" },
      { key: "2", text: "In melting ice" },
      { key: "3", text: "In boiling oil" },
      { key: "4", text: "In melting dry ice" },
    ],
    correctOption: "2",
  },
  {
    questionText:
      "Which rule is useful for estimating the surface temperature of celestial bodies",
    options: [
      { key: "1", text: "Stefan-Boltzmann law" },
      { key: "2", text: "Joule's law" },
      { key: "3", text: "Newton's law of cooling" },
      { key: "4", text: "Wien's law" },
    ],
    correctOption: "4",
  },
];

export async function seedHeatEnergy(
  prisma: PrismaClient,
  subjectId: string,
  chapterId: string,
) {
  console.log("Seeding Heat Energy Content...");

  // 1. Create the Article Lesson
  await prisma.lesson.upsert({
    where: {
      chapterId_slug: { chapterId: chapterId, slug: "theory" },
    },
    update: {
      title: "Heat Energy",
      articleHtml: ARTICLE_HTML,
    },
    create: {
      chapterId: chapterId,
      subjectId: subjectId,
      title: "Heat Energy",
      slug: "theory",
      type: LessonType.ARTICLE,
      articleHtml: ARTICLE_HTML,
      order: 1,
      accessTier: "FREE",
      isActive: true,
    },
  });
  console.log("✅ Seeded Theory Article Lesson");

  // 2. Create Questions
  console.log("Seeding MCQs...");
  let count = 0;
  for (const q of QUESTIONS) {
    const existing = await prisma.question.findFirst({
      where: {
        chapterId: chapterId,
        questionText: q.questionText,
      },
    });

    if (!existing) {
      await prisma.question.create({
        data: {
          subjectId: subjectId,
          chapterId: chapterId,
          questionText: q.questionText,
          options: q.options,
          correctOption: q.correctOption,
          difficulty: Difficulty.MEDIUM,
          examTypes: ["SSC_CGL", "SSC_CHSL", "SSC_MTS", "SSC_CPO", "SSC_GD"],
          isActive: true,
          tags: ["Physics", "Heat Energy"],
        },
      });
      count++;
    }
  }

  console.log(`✅ Seeded ${count} new MCQs!`);

  // 3. Create a Practice Set
  console.log("Seeding Practice Set...");
  const practiceSet = await prisma.practiceSet.upsert({
    where: { id: "seed-heat-energy-ps" },
    update: {
      questionCount: QUESTIONS.length,
    },
    create: {
      id: "seed-heat-energy-ps",
      title: "Heat Energy Practice Quiz",
      subjectId: subjectId,
      chapterId: chapterId,
      questionCount: QUESTIONS.length,
      accessTier: AccessTier.FREE,
      order: 2,
      isActive: true,
    },
  });

  // 4. Link questions to the practice set
  const allChapterQuestions = await prisma.question.findMany({
    where: { chapterId: chapterId },
  });

  for (let i = 0; i < allChapterQuestions.length; i++) {
    const question = allChapterQuestions[i];
    await prisma.practiceSetQuestion.upsert({
      where: {
        practiceSetId_questionId: {
          practiceSetId: practiceSet.id,
          questionId: question.id,
        },
      },
      update: { order: i + 1 },
      create: {
        practiceSetId: practiceSet.id,
        questionId: question.id,
        order: i + 1,
      },
    });
  }

  console.log("✅ Seeded Practice Set!");
  console.log("🎉 Successfully seeded Heat Energy content!");
}
